version: "3,8"
services:
  multi-timer:
    build: .
    command: sh -c "yarn install && yarn dev"
    volumes:
      - "./:/multi-timer"
    ports:
      - "5173:5173"
      - "4173:4173"
    tty: true
    stdin_open: true
    init: true
